config/routes.rb
Rails.application.routes.draw do
  resources :swift_api_keys
  resources :items
  root 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/swift_api_key.rb
class SwiftApiKey < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
require 'httparty'
require 'json'

class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    #api_key = "cb8d3966-e1c6-4429-a8cf-b615523481c4"

    @item = Item.new(item_params)

    @swift_api_key = SwiftApiKey.first

    api_key = @swift_api_key.key

    HTTParty.post("https://app.getswift.co/api/v2/deliveries",
          {
            :body => {
                        "apiKey": api_key,
                        "booking":{
                            "items": [{
                                "quantity": @item.quantity,
                                "sku": @item.sku,
                                "description": @item.description,
                                "price": @item.price
                            }],
                            "pickupDetail": {
                                "name": "Marko",
                                "phone": "604 356 8259",
                                "address": "301 Maude Road, Port Moody, V3H5B1"
                            },
                            "dropoffDetail": {
                                "name": @item.name,
                                "phone": @item.phone,
                                "address": @item.address
                            }
                        }
                    }.to_json,
            :headers => { 'Content-Type' => 'application/json' }
          }
      )

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :phone, :address, :quantity, :description, :price, :sku)
    end
end

app/controllers/swift_api_keys_controller.rb
class SwiftApiKeysController < ApplicationController
  before_action :set_swift_api_key, only: [:show, :edit, :update, :destroy]

  # GET /swift_api_keys
  # GET /swift_api_keys.json
  def index
    @swift_api_keys = SwiftApiKey.all
  end

  # GET /swift_api_keys/1
  # GET /swift_api_keys/1.json
  def show
  end

  # GET /swift_api_keys/new
  def new
    @swift_api_key = SwiftApiKey.new
  end

  # GET /swift_api_keys/1/edit
  def edit
  end

  # POST /swift_api_keys
  # POST /swift_api_keys.json
  def create
    @swift_api_key = SwiftApiKey.new(swift_api_key_params)

    respond_to do |format|
      if @swift_api_key.save
        format.html { redirect_to @swift_api_key, notice: 'Swift api key was successfully created.' }
        format.json { render :show, status: :created, location: @swift_api_key }
      else
        format.html { render :new }
        format.json { render json: @swift_api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swift_api_keys/1
  # PATCH/PUT /swift_api_keys/1.json
  def update
    respond_to do |format|
      if @swift_api_key.update(swift_api_key_params)
        format.html { redirect_to @swift_api_key, notice: 'Swift api key was successfully updated.' }
        format.json { render :show, status: :ok, location: @swift_api_key }
      else
        format.html { render :edit }
        format.json { render json: @swift_api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swift_api_keys/1
  # DELETE /swift_api_keys/1.json
  def destroy
    @swift_api_key.destroy
    respond_to do |format|
      format.html { redirect_to swift_api_keys_url, notice: 'Swift api key was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swift_api_key
      @swift_api_key = SwiftApiKey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swift_api_key_params
      params.require(:swift_api_key).permit(:key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/swift_api_keys_helper.rb
module SwiftApiKeysHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <small>Dropoff Details</small>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <hr>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Description</th>
      <th>Price</th>
      <th>Sku</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.quantity %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= item.sku %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @item.sku %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>V1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/swift_api_keys/_form.html.erb
<%= form_for(@swift_api_key) do |f| %>
  <% if @swift_api_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@swift_api_key.errors.count, "error") %> prohibited this swift_api_key from being saved:</h2>

      <ul>
      <% @swift_api_key.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/swift_api_keys/edit.html.erb
<h1>Editing Swift Api Key</h1>

<%= render 'form' %>

<%= link_to 'Show', @swift_api_key %> |
<%= link_to 'Back', swift_api_keys_path %>

app/views/swift_api_keys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Swift Api Keys</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @swift_api_keys.each do |swift_api_key| %>
      <tr>
        <td><%= swift_api_key.key %></td>
        <td><%= link_to 'Show', swift_api_key %></td>
        <td><%= link_to 'Edit', edit_swift_api_key_path(swift_api_key) %></td>
        <td><%= link_to 'Destroy', swift_api_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Swift api key', new_swift_api_key_path %>

app/views/swift_api_keys/new.html.erb
<h1>New Swift Api Key</h1>

<%= render 'form' %>

<%= link_to 'Back', swift_api_keys_path %>

app/views/swift_api_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @swift_api_key.key %>
</p>

<%= link_to 'Edit', edit_swift_api_key_path(@swift_api_key) %> |
<%= link_to 'Back', swift_api_keys_path %>